#!/usr/bin/env bash
# To display "Best School" 10 times using a while loop 
# Then on the 9tth iteration display "HI" before "Best School"

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "HI"
	fi
	echo "Best School"
	(( count++ ))
done
